config/routes.rb
Rails.application.routes.draw do
 
  devise_for :authors
  root to: 'blog/posts#index' 

   namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put'/info' => 'accounts#update_info', as: :info
    put'/change_password' => 'accounts#change_password',  as: :change_password
  
    resources :posts do
    
    put 'publish' => 'posts#publish', on: :member
    put 'unpublish' => 'posts#unpublish', on: :member
     end
   end

  scope module: 'blog' do 
    get 'about' => 'pages#about', as: :about 
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index' , as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :bigint(8)        not null, primary key
#  name                   :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

         has_many :posts
end
 

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :bigint(8)        not null, primary key
#  title            :string(255)
#  body             :text(65535)
#  description      :text(65535)
#  slug             :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string(255)
#  author_id        :integer
#  puplished        :boolean          default(FALSE)
#  published_at     :datetime
#
 
class Post < ApplicationRecord
    extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author
  

scope :most_recent,->{order(published_at: :desc) }
scope :published, -> { where(published: true) }
def should_generate_new_friendly_id?
    title_changed?
end

def display_day_published
    if published_at.present?
    "published #{published_at.strftime('%-b %-d %-Y')}"
    else
        "Not published yet."
    end
end

def publish
    update(published: true, published_at: Time.now)
end

def unpublish
    update(published: false, published_at: nil)
end    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    layout 'author'
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
    before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
    class AccountsController < AuthorController

        def edit 
        end
        
        def update_info
            current_author.update(author_info_params)
            redirect_to authors_account_path
        end  

        def change_password
            if current_author.valid_password?(author_password_params[:current_password])
                current_author.update(
                    password: author_password_params[:new_password],
                    password_confirmation: author_password_params[:nwe_password_confirmation]
                )
                end
                redirect_to authors_account_path

        end    
        
        private

        def author_info_params
            params.require(:author).permit(:name, :email, :bio)
        end    

        def author_password_params
            params.require(:author).permit(:current_password, :new_password, :new_confirmation_password)
        end    

    end 
end        

app/controllers/authors/posts_controller.rb
module Authors
    class PostsController < AuthorController
        before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
      
        # GET /posts
        # GET /posts.json
        def index
          @posts = current_author.posts.most_recent
        end
      
        # GET /posts/1
        # GET /posts/1.json
        def show
        end
      
        # GET /posts/new
        def new
          @post = current_author.posts.new
        end
      
        # GET /posts/1/edit
        def edit
        end

        def publish
           @post.publish
           redirect_to authors_posts_url
        end 

        def unpublish
          @post.unpublish
          redirect_to authors_posts_url
        end 
      
        # POST /posts
        # POST /posts.json
        def create
          @post = current_author.posts.new(post_params)
      
          respond_to do |format|
            if @post.save
              format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
              format.json { render :show, status: :created, location: @post }
            else
              format.html { render :new }
              format.json { render json: @post.errors, status: :unprocessable_entity }
            end
          end
        end
      
        # PATCH/PUT /posts/1
        # PATCH/PUT /posts/1.json
        def update
          respond_to do |format|
            if @post.update(post_params)
              format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
              format.json { render :show, status: :ok, location: @post }
            else
              format.html { render :edit }
              format.json { render json: @post.errors, status: :unprocessable_entity }
            end
          end
        end
      
        # DELETE /posts/1
        # DELETE /posts/1.json
        def destroy
          @post.destroy
          respond_to do |format|
            format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
            format.json { head :no_content }
          end
        end
      
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_post
            @post = current_author.posts.friendly.find(params[:id])
          end
      
          # Never trust parameters from the scary internet, only allow the white list through.
          def post_params
            params.require(:post).permit(:title, :body, :description , :banner_image_url )
          end
      end
      
    
end

app/controllers/blog/pages_controller.rb
module Blog
    class PagesController < BlogController

        def about  
        end
    
        def contact
        end
    
    end
end

app/controllers/blog/posts_controller.rb
module Blog
    class PostsController < BlogController
       
        # GET /posts
        # GET /posts.json
        def index
          @posts = Post.most_recent.published.paginate(:page => params[:page], per_page:3)
        end
      
        # GET /posts/1
        # GET /posts/1.json
        def show
          @post = Post.friendly.find(params[:id])
        end
   
      end
      
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/accounts/edit.html.erb
<div class="row">

<!-- basic info -->

    <%= form_tag authors_info_path, method: :put  do %>
        <%= fields_for :author do |f| %>
            <div class="col-md-6">
                <div class="card card1">
                    <div class="card-block"> 
                        <div class="card-title">
                            Basic Info
                        </div>
                    </div>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <div class="field">
                                <%= f.label :name %>
                                <%= f.text_field :name, value: current_author.name,  class: 'form-control' %>
                            </div>
                        </li>
                        <li class="list-group-item">
                                <div class="field">
                                    <%= f.label :email %>
                                    <%= f.email_field :email, value: current_author.email, class: 'form-control' %>
                                </div>
                        </li>  
                        <li class="list-group-item">
                                <div class="field">
                                    <%= f.label :bio %>
                                    <%= f.text_area :bio, value: current_author.bio, class: 'form-control' %>
                                </div>
                        </li>
                        <li class="list-group-item">
                            <%= f.submit "Update info", class: 'btn btn-primary' %>    
                        </li>
                        
                    </ul> 
                
                </div>
            </div>
        <% end %> 
    <% end %>

<!-- change password -->
    <%= form_tag authors_change_password_path, method: :put do %>
        <%= fields_for :author do |f| %>
            <div class="col-md-6">
                <div class="card card1">

                    <div class="card-block"> 
                        <div class="card-title">
                            Change Your Password
                        </div>
                    </div>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <div class="field">
                                <%= f.label :password %>
                                <%= f.password_field :password,  class: 'form-control' %>
                            </div>
                        </li>
                        <li class="list-group-item">
                                <div class="field">
                                    <%= f.label :new_password %>
                                    <%= f.password_field :new_password, class: 'form-control' %>
                                </div>
                        </li>
                        <li class="list-group-item">
                                <div class="field">
                                    <%= f.label :new_password_confirmation %>
                                    <%= f.password_field :new_password_confirmation,  class: 'form-control' %>
                                </div>
                        </li>
                         <li class="list-group-item">
                            <%= f.submit "Change password", class: 'btn btn-warning' %>    
                        </li>
                    </ul> 
                </div>
            </div>
        <% end %>        
    <% end %>
</div>

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url ) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">

                   <!-- <div class="card" style="width: 18rem;">
              <img class="card-img " src="..." alt="Card image cap"> -->
              <div class="card">
              <div class="card-block">
              <% if @post.new_record? %>
                <h5 class="card-title"><%= yield(:page_title) %></h5>
                <% else %>
                <h5 class="card-title">
                <b>Edit</b>
                <span class="thin-text"><%= @post.title %></span>
                </h5>
                <% end %>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                       <div class="field">
                          <%= form.label :title %>
                          <%= form.text_field :title, class: 'form-control' %>
                       </div>
                </li>
                <li class="list-group-item">
                          <div class="field">
                            <%= form.label :banner_image_url %>
                            <%= form.text_field :banner_image_url, class: 'form-control' %>
                          </div>
                </li>
                <li class="list-group-item">
                          <div class="field">
                            <%= form.label :description %>
                            <%= form.text_area :description, class: 'form-control' %>
                          </div>
                </li>
                 <li class="list-group-item">
                    <div class="actions">
                      <%= form.submit " Save blog post ", class: 'btn btn-success btn-lg btn-blog' %>
                    </div>   
                </li>
              </ul> 
            </div>

            <% if @post.persisted? %>
             <%= link_to 'Show', @post %> |
             <% end %>
             <%= link_to 'Back', authors_posts_path %>

    </div>
     <div class="col-md-8">
 <div class="field">
    <%= form.text_area :body %>
  </div>
     </div>
    </div>


<% end %>

app/views/authors/posts/_post.html.erb
<tr>
<td><%= link_to post.title, authors_post_path(post) %> </td>
<td></td>
<% if post.published? %>
<td><%= link_to 'Unpublish', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %> </td>
<% else %>
<td><%= link_to 'Publish', publish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-success' %> </td>
<% end %>
<td><%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %> </td>
<td><%= link_to 'Remove', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %> </td>

</tr> 

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}")  %>
<% provide(:author, 'active')  %>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'All Post')  %>
<% provide(:author, 'active')  %>
<br>
<div class="row">

<div> 
<%= link_to 'New post', new_authors_post_path, class: 'btn btn-primary btn-lg'%>
</div>

<br>
<br>
<table class="table table-striped">
<tr>
<th colspan="5">Title</th>
</tr>
<%= render @posts %>
</table>
</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'new post')  %>
<% provide(:author, 'active')  %>


<%= render 'form', post: @post, url: authors_posts_url %>

<%= link_to 'Back', authors_posts_path %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title)  %>
<% provide(:author, 'active')  %>

<div>
<%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
<%= link_to 'Remove', authors_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
</div>

<div class="row">
<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xz-center">
<h1><%=@post.title %></h1>
<p><%= @post.display_day_published %></p>
<%= @post.body.html_safe %>
</div>
</div>

app/views/blog/pages/about.html.erb
<% provide(:about_active, 'active')  %>


<h1> About page </h1>

app/views/blog/pages/contact.html.erb
<% provide(:contact_active, 'active')  %>


<h1> Contact page </h1>

app/views/blog/posts/_post.html.erb
<div class='col-sm-6 col-lg-4'>
  <div class="card" style="width: 18rem;">
  <div class="card-topper card-img-top" style='background-image: url(<%=post.banner_image_url%>);'></div>
  
  <div class="card-body">
     <h4 class="card-title"><%= link_to post.title, post %></h4>
      <p class="published-date"><%= post.display_day_published %></p>
      <p class="card-text"><%= truncate(post.description, length: 130) %></p>
      <%= link_to 'Read', post, class: 'btn btn-read' %>
  </div>
</div>
</div>

app/views/blog/posts/index.html.erb
<div class="row">
<%= render @posts %>
</div>

<div class="next apple_pagination">
<%= will_paginate @posts, container: false %> 
</div>

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title)  %>
<% provide(:blog_active, 'active')  %>

<div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xz-center">
        <h1><%=@post.title %></h1>
        <p> <%= @post.display_day_published %> </p>
        <%= @post.body.html_safe %>

        <noscript>
        Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>

        </noscript>

    </div>
</div>

<div id="disqus_thread"></div>
    <script>

        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
        
        
        var disqus_config = function () {
        this.page.url = '<%= request.original_url %>';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = '<%= @post.slug %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://codeapp-1.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
    </script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
    <li class="nav-item">
         <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)} " %>
      </li>
      <li class="nav-item">
         <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
      </li>
        
 
        <% if author_signed_in? %>
        

          <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle <%= yield(:author) %>" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Author
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'My posts', authors_posts_path, class: "dropdown-item #{yield(:author)}" %>
          <%= link_to 'Account', authors_account_path, class: "dropdown-item " %>
          <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "dropdown-item" %>

          
        </div>
      </li>

        <% end %>


      <!--
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      -->
    </ul>
  </div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:page_title) %> | Code</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
    

  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <br>
      <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% end %>
    <div class="container <%= controller_name %> <%=action_name %>">
      <%= yield %>
    </div> 
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:page_title) %> | Code</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  </head>

  <body>
  <%=render"layouts/navbar" %>
    <div class="container <%= controller_name %> <%=action_name %>">
      <%= yield %>
    </div> 
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>